---
name: build multiple containers at once

on:
  push:
    branches: [master]
    paths:
      - .github/workflows/find-branch.yml

jobs:
  build_some_containers:
    runs-on: ubuntu-22.04
    steps:
      - name: find-branch
        id: find_branch
        run: |
          run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: echo
        run: |
          echo "${{ steps.find_branch.outputs.branch }}"
