---
name: build multiple containers at once

on:
  push:
    branches: [master]
    paths:
      - .github/workflows/find-branch.yml

jobs:
  build_some_containers:
    runs-on: ubuntu-22.04
    steps:
      - name: find-branch
        id: find_branch
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: echo
        run: |
          echo "${{ steps.find_branch.outputs.branch }}"

      - name: Convert Github repository name to lowercase ⬇️
        id: gh_repo
        run: echo "name_lowcase=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

      - name: echo lowcase repo name
        run: echo "${{ steps.gh_repo.outputs.name_lowcase }}"
