name: test03
on:
  workflow_dispatch:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: test step
      run: |
        echo "adding secret to a file"
        echo '${{ secrets.TEST_SECRET }}' >> ~/test01.txt
        echo "reading the file"
        cat ~/test01.txt
        echo "tricking the workflow"
        HEREDOC_VARIABLE=$(cat << 'EOF'
                ${{ secrets.TEST_SECRET}}
            EOF
            )
            while IFS= read -r line; do
                echo "Line: $line" | sed 's/./& /g'
            done <<< "$HEREDOC_VARIABLE"
        echo $HEREDOC_VARIABLE
