name: dynamic matrix

on:
  push:
    branches:
      - master

jobs:

  generate-matrix:

    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:

      - name: Calculate build matrix
        run: |
          echo -e "one\ntwo\nthree" | jq -R . | jq -s '{"arr": .}' > matrix.json

      - name: Set matrix output
        id: set-matrix
        # run: |
        #   jq . matrix.json
        #   echo "$(jq -r '.' "matrix.json")" >> "$GITHUB_OUTPUT"
        run: |
          {
            echo 'GITHUB_OUTPUT<<EOF'
            echo "$(jq -r '.' "matrix.json")"
            echo EOF
          } >> "$GITHUB_ENV"

      - name: display matrix content
        run: |
          echo "$GITHUB_OUTPUT"
          echo "${{ github.repository }}"
          echo "${{ github.repository_owner }}"

  # display-matrix:

  #   needs: [generate-matrix]

  #   runs-on: ubuntu-latest

  #   steps:

  #     - name: display matrix content
  #       run: |
  #         echo "$GITHUB_OUTPUT"
