---
name: build containers on every push to devel branch

on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

jobs:

  build_base:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        container: [base]
        python_version: ["3.9", "3.10", "3.11"]
    
    steps:

      - name: test
        run: |
          echo "${{ github.ref_name }}"
