---
name: build containers on every push to devel branch

on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

jobs:

  build_base:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        container: [base]
        python_version: ["3.9", "3.10", "3.11"]
        include:
          - python_version: ["3.9", "3.10"]
            container_tags: ${{ matrix.python_version }}
          - python_version: "3.11"
            container_tags: ${{ matrix.python_version }},latest
    steps:

      - name: test
        run: |
          echo "{{ matrix.container_tags }}"
