name: test03
on:
  workflow_dispatch:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: test step
      run: |
        echo "${{ secrets.TEST_SECRET }}" >> ~/test01.txt
        cat ~/test01.txt
